# Generated by Django 6.0.1 on 2026-01-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_orden_itemorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARACION', 'En Preparación'), ('LISTO', 'Listo para Retirar'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pedido'),
        ),
    ]
