# Generated by Django 5.2.10 on 2026-01-15 13:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_producto_imagen2_producto_imagen3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen Principal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Imagen 3'),
        ),
    ]
